name: AutoSell
version: 2.0.3
main: me.fatpigsarefat.autosell.AutoSell
author: fatpigsarefat

commands:
  autosell:
    description: AutoSell
    usage: /autosell
    permission: autosell.command

permissions:
  autosell.command:
    description: Autosell command
  autosell.create:
    description: Permission to create autosell chest
  autosell.admin:
    description: Bypass autosell restrictions